#!/usr/bin/env bash

POSTGRES_CERTIFICATES_PATH=${POSTGRES_CERTIFICATES_PATH:="/.postgresql"}

mkdir -p $POSTGRES_CERTIFICATES_PATH && chmod g+w $POSTGRES_CERTIFICATES_PATH

if [ "$POSTGRES_ENABLE_SSL_AUTH" = "true" ]
then
  cp $POSTGRES_CERTS_MOUNT_PATH/* $POSTGRES_CERTIFICATES_PATH
  chmod 400 $POSTGRES_CERTIFICATES_PATH/*.key
fi

node ./index.js "$@"
