{{- $releaseName := .Release.Name -}}
{{- $chartName := include "planet-dumper.name" . -}}
{{- $tracingUrl := include "planet-dumper.tracingUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-configmap
data:
  {{- with .Values.postgres }}
  PGHOST: {{ .host }}
  PGPORT: {{ .port | default 5432 | quote }}
  PGDATABASE: {{ .database }}
  POSTGRES_ENABLE_SSL_AUTH: {{ .sslAuth.enabled | quote }}
  {{- if .sslAuth.enabled }}
  POSTGRES_CERTS_MOUNT_PATH: {{ .sslAuth.mountPath | quote }}
  {{- end }}
  {{- end }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote | default "false" }}
  TELEMETRY_TRACING_ENABLED: {{ .Values.env.tracing.enabled | quote }}
  {{- if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  TELEMETRY_TRACING_RATIO: {{ .Values.env.tracing.ratio | quote }}
  {{- end }}
  HTTP_CLIENT_TIMEOUT: {{ .Values.env.httpClient.timeout | quote }}
  PG_DUMP_VERBOSE: {{ .Values.env.pgDump.verbose | quote }}
  NG_DUMP_VERBOSE: {{ .Values.env.ngDump.verbose | quote }}
  NG_DUMP_MAX_CONCURRENCY: {{ .Values.env.ngDump.maxConcurrency | quote }}
{{- end -}}
