{{- $releaseName := .Release.Name -}}
{{- $chartName := include "planet-dumper.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-configmap
data:
  {{- with .Values }}
  # general
  DUMP_NAME_PREFIX: {{ .dumpNamePrefix | default "" | quote }}
  # postgres
  POSTGRES_HOST: {{ .dbConfig.host }}
  POSTGRES_DB: {{ .dbConfig.database }}
  POSTGRES_PORT: {{ .dbConfig.port | quote }}
  {{- if .dbConfig.sslAuth.enabled }}
  POSTGRES_ENABLE_SSL_AUTH: "true"
  POSTGRES_CERTIFICATES_PATH: {{ .dbConfig.sslAuth.path }}
  POSTGRES_SSL_CERT: {{ .dbConfig.sslAuth.path }}/{{ .dbConfig.sslAuth.certFileName }}
  POSTGRES_SSL_KEY: {{ .dbConfig.sslAuth.path }}/{{ .dbConfig.sslAuth.keyFileName }}
  POSTGRES_SSL_ROOT_CERT: {{ .dbConfig.sslAuth.path }}/{{ .dbConfig.sslAuth.caFileName }}
  {{- else }}
  POSTGRES_ENABLE_SSL_AUTH: "false"
  {{- end }}
  # object storage
  {{- if .objectStrorageConfig.enabled }}
  {{- if .objectStrorageConfig.enableInternal }}
  OBJECT_STORAGE_HOST: {{ $releaseName }}-minio
  {{- else }}
  OBJECT_STORAGE_HOST: {{ .objectStrorageConfig.host }}
  {{- end }}
  UPLOAD_TO_OBJECT_STORAGE: "true"
  OBJECT_STORAGE_PORT: {{ .objectStrorageConfig.port | quote }}
  OBJECT_STORAGE_PROTOCOL: {{ .objectStrorageConfig.protocol }}
  OBJECT_STORAGE_BUCKET: {{ .objectStrorageConfig.bucketName }}
  {{- if .objectStrorageConfig.sslAuth.enabled }}
  OBJECT_STORAGE_USE_SSL: "true"
  {{- end }}
  {{- if .objectStrorageConfig.sslAuth.shouldVerify }}
  OBJECT_STORAGE_VERIFY_ROOT_CERT: "true"
  {{- end }}
  {{- else }}
  UPLOAD_TO_OBJECT_STORAGE: "false"
  {{- end }}
  # dump-server
  {{- if .dumpServerConfig.enabled }}
  UPLOAD_TO_DUMP_SERVER: "true"
  DUMP_SERVER_HOST: {{ .dumpServerConfig.host }}
  DUMP_SERVER_PORT: {{ .dumpServerConfig.port | quote }}
  DUMP_SERVER_PROTOCOL: {{ .dumpServerConfig.protocol }}
  DUMP_SERVER_PATH: {{ .dumpServerConfig.path }}
  {{- else }}
  UPLOAD_TO_DUMP_SERVER: "false"
  {{- end }}
  {{- end -}}
{{- end -}}
