{{- $releaseName := .Release.Name -}}
{{- $chartName := include "planet-dumper.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}-secret
    environment: {{ include "planet-dumper.environment" . }}
    release: {{ $releaseName }}
    {{- include "planet-dumper.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.dbConfig }}
  POSTGRES_USER: {{ .username | b64enc }}
  POSTGRES_PASSWORD: {{ .password | b64enc }}
  {{- end -}}
  {{- if .Values.objectStrorageConfig.enabled -}}
  {{- if .Values.objectStrorageConfig.enableInternal -}}
  {{- with .Values.minio }}
  OBJECT_STORAGE_ACCESS_KEY_ID: {{ .accessKey.password | b64enc }}
  OBJECT_STORAGE_SECRET_ACCESS_KEY: {{ .secretKey.password | b64enc }}
  {{- end -}}
  {{- else -}}
  {{- with .Values.objectStrorageConfig }}
  OBJECT_STORAGE_ACCESS_KEY_ID: {{ .accessKey | b64enc }}
  OBJECT_STORAGE_SECRET_ACCESS_KEY: {{ .secretKey | b64enc }}
  {{- end -}}
  {{- end -}}
  {{- end -}}
  {{- if .Values.dumpServerConfig.enabled }}
  DUMP_SERVER_TOKEN: {{ .Values.dumpServerConfig.token | b64enc }}
  {{- end }}
{{- end }}
