apiVersion: v2
name: planet-dumper
description: A Helm chart for Kubernetes
type: application
version: 0.1.0


dependencies:
- name: minio
  version: 6.2.0
  repository: https://charts.bitnami.com/bitnami
  condition: enableInternalObjectStorage