global:
  cloudProvider: {}
  # environment: development
  # cloudProvider:
  #   name: minikube
  #   dockerRegistryUrl: 'some_url'

environment: development
cloudProvider:
  name: azure
  dockerRegistryUrl: 'some_url'

enabled: true
schedule: '* */1 * * *'
image:
  repository: 'planet-dumper'
  tag: 'v1'
dbConfig:
  host: potgresHost
  username: postgres
  password: '1234'
  database: openstreetmap
  port: 5432
objectStrorageConfig:
  enabled: true
  enableInternal: false
  host: s3Host
  port: 9000
  protocol: http
  accessKey: accessKey
  secretKey: secretKey
  bucketName: planet-dumps
dumpServerConfig:
  enabled: true
  host: dumpServerHost
  port: 8080
  protocol: http
  path: dumps
  token: 'dQw4w9WgXcQ'
dumpNamePrefix: 'planet-dump'
resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

#internal object storage
minio:
  accessKey:
    password: internalAccessKey
  secretKey:
    password: internalSecretKey
  service:
    type: NodePort
  defaultBuckets: planet-dumps
