global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development

jobAnnotations: {}
podAnnotations: {}
cronAnnotations: {}

cloudProvider:
  flavor: openshift
  dockerRegistryUrl: my-registry-url.io

image:
  repository: planet-dumper
  # Overrides the image tag whose default is the chart appVersion.
  # tag: 'latest'
  pullPolicy: IfNotPresent

job:
  enabled: true
  apiVersion: 'batch/v1' # depends on openshift version batch/v1 or batch/v1beta1
  restartPolicy: OnFailure
  ttlSecondsAfterFinished: 60
  backoffLimit: 6

cron:
  enabled: false
  apiVersion: 'batch/v1' # depends on openshift version batch/v1 or batch/v1beta1
  restartPolicy: OnFailure
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200

resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

env:
  logLevel: info
  logPrettyPrintEnabled: false
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
    ratio: 1
  httpClient:
    timeout: 1000
  pgDump:
    verbose: false
  ngDump:
    verbose: false
    maxConcurrency: 16
  osmium:
    verbose: false
    progress: false

postgres:
  host: localhost
  username: postgres
  password: postgres
  database: openstreetmap
  # port: 5432
  sslAuth:
    enabled: false
    secretName: secret-name
    mountPath: '/tmp/certs-postgres'

s3:
  accessKey: accessKey
  secretKey: secretKey
  host: s3Host
  port: 9000
  protocol: http
  bucketName: planet-dumps
  acl: private
  upload:
    concurrency: 4
    partSize: 5 # in mb

pvc:
  enabled: true
  name: pvc-name

cli:
  command: 'create'
  outputFormat: dump_{state}_{timestamp}.pbf
  stateSource: https://osm-diffs.com/state.txt # replication url or specific state number
  cleanupMode: 'none'
  create:
    resume: false
    info: false
    dumpServer:
      enabled: true
      endpoint: http://dump-server.com
      attachHeaders: false
      headers: X-API-KEY=apikey

arstotzka:
  enabled: false
  serviceId: id
  networkCM: arstotzka-network-configmap
  mediator:
    timeout: 10000
    retryStrategy:
      enabled: false
      # retries: 3
      # shouldResetTimeout: false
      # isExponential: false
      # delay: 100
