global:
  environment: development
  cloudProvider:
    name: minikube
    dockerRegistryUrl: 'some_url'

enabled: true
enableInternalObjectStorage: true
schedule: '*/1 * * * *'
image:
  repository: 'planet-dumper'
  tag: 'v1'
replicaCount: 1
env:
  # dumpNamePrefix: planet_dump
  db:
    host: postgresHost
    username: postgres
    password: '1234'
    database: openstreetmap
    port: 5432
  objectStrorage:
    enabled: true
    value:
      host: hostName
      port: 9000
      protocol: http
      accessKey: accessKey
      secretKey: secretKey
      bucketName: dumps
resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

#internal object storage
minio:
  accessKey:
    password: accessKey
  secretKey:
    password: secretKey
  service:
    type: NodePort
  defaultBuckets: dumps
